name: Selenium Tests

on:
  push:
    branches:
      - master

jobs:
  selenium-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Download GeckoDriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
          tar -xzf geckodriver-v0.30.0-linux64.tar.gz

      - name: Set up Firefox WebDriver
        run: |
          mkdir -p $HOME/bin
          mv geckodriver $HOME/bin
          export PATH=$HOME/bin:$PATH

      - name: Run Selenium Script
        run: python index.py
