name: Selenium Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Selenium
        run: |
          pip install selenium

      - name: Install bs4
        run: |
          pip install bs4

      - name: Install GeckoDriver
        run: |
          mkdir -p path/to
          wget -q "https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz" -O path/to/geckodriver.tar.gz
          tar -xzf path/to/geckodriver.tar.gz -C path/to/
          chmod +x ./geckodriver
          export PATH=$PATH:$(pwd)/

      - name: Run Selenium Tests
        run: python index.py
